name: Build and Install Dependencies

on:
  push:
    branches:
      - main       # Trigger on push to the main branch
  pull_request:
    branches:
      - main       # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest   # Run the job on the latest Ubuntu environment

    steps:
      # Step 1: Checkout the repository's code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python version
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Set the Python version for the build

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the build script (build.sh) to install necessary packages
      - name: Run build script
        run: |
          chmod +x ./build.sh   # Ensure the build script is executable
          ./build.sh            # Run the build script
