name: Build and Install Dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest   # Specify your OS

    steps:
      # Step 1: Checkout the repository's code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python version
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 'latest'  # Use the latest Python version

      # Step 3: Install necessary system dependencies for mysqlclient
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmysqlclient-dev

      # Step 4: Set environment variables for mysqlclient
      - name: Set environment variables for mysqlclient
        run: |
          echo "MYSQLCLIENT_CFLAGS=-I/usr/include/mysql" >> $GITHUB_ENV
          echo "MYSQLCLIENT_LDFLAGS=-L/usr/lib/mysql" >> $GITHUB_ENV

      # Step 5: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 6: Run the build script (build.sh) to install necessary packages
      - name: Run build script
        run: |
          chmod +x ./build.sh   # Ensure the build script is executable
          ./build.sh            # Run the build script
